### ISSUE TITLE
The Project To-Do List

### ISSUE THREAD

**Issue by ahamal** [ahamal/witt#1]
02/28
- [ ] Setup a Github account
- [ ] Setup a simple nodejs/socket.io ‘hello world’ web server, linked to the code in the github account, in a test environment.
- [ ] Draw and spec out the detailed wireframes for the client side pages.

03/06
- [ ] Draw and spec out the Database Schema
- [ ] Draw and spec out the Use Case Diagram
- [ ] Add project details to Github

03/13
- [ ] Setup mongodb.
- [ ] Implement database schemas using mongoose.
- [ ] Write boilerplate and tests APIs on socket.io server.
- [ ] Write boilerplate code for the front-end app.

03/20
- [ ] Write APIs on the server side for login/logout and updating user’s profile.
- [ ] Add web views on the client side for Login/Logout, and editing user’s profile.

03/27
- [ ] Write APIs on the server side for adding and searching for the channels.
- [ ] Add web views on the client side to add and look for the channels.

Milestone 2 Deliverables
- [ ] An app where a user can login, edit profile, add/lookup channels.
- [ ] A placeholder for the channel page.

04/03
- [ ] Write APIs on the server side to add the map support and channel filtering.
- [ ] Add web views on the client side to enable filtering and maps for channels.

04/10
- [ ] Write APIs on the server side that allows users to add embedded web pages. 
- [ ] Write APIs on the server side that allows users to chat on the channels
- [ ] Add web views on the client side for embedding web pages or placeholder persistent view.
- [ ] Add web views to enable simple chat.

04/17
- [ ] Add channel permission/rules on the channel page by channel admin.
- [ ] Add a simple WYSIWYG text-editor for a native persistent view.
- [ ] Write APIs on the backend to support channel permissions, and persistent view.

04/24
- [ ] Deploy the app in a test environment.
- [ ] Have the app  tested with the interested peers.
- [ ] Fix any bugs that comes up during testing.

05/01
- [ ] Add finishing touches to the websites, such as contact info, and about pages.
- [ ] Deploy the website to a production environment, where it could be used by the public.
- [ ] Write the final paper on the project as explained here.
- [ ] Create a final presentation video that walks through the application and demonstrates how it works.
